fix: model-service not having a single source of truth

diff --git a/.github/workflows/release-image.yml b/.github/workflows/release-image.yml
--- a/.github/workflows/release-image.yml
+++ b/.github/workflows/release-image.yml
@@ -16,6 +16,29 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      
+      - name: Read version from pyproject.toml
+        id: pyproject
+        run: |
+          PYPROJECT_VERSION=$(grep -E '^version' pyproject.toml | head -1 | sed 's/version *= *"//;s/"//')
+          echo "PYPROJECT_VERSION=$PYPROJECT_VERSION" >> $GITHUB_ENV
+          echo "pyproject version: $PYPROJECT_VERSION"
+      
+      - name: Extract version from tag
+        id: tag
+        run: |
+          TAG="${GITHUB_REF_NAME}"        # e.g. v1.2.3
+          TAG_VERSION="${TAG#v}"          # strip v -> 1.2.3
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
+          echo "Tag version: $TAG_VERSION"
+      
+      - name: Validate version consistency
+        run: |
+          if [ "$PYPROJECT_VERSION" != "$TAG_VERSION" ]; then
+            echo "ERROR: Tag version ($TAG_VERSION) different than pyproject.toml version ($PYPROJECT_VERSION)"
+            exit 1
+          fi
+          echo "Version Match ! PYPROJECT_VERSION and TAGVERSION, ($TAG_VERSION)"
 
       - name: Login to GHCR
         uses: docker/login-action@v3
